# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd85fba461d1432519056a21f114fe071ed7f5556ee3c8b8202144e8d0a5cd72e7d9ff183705300053d3c9d94b4908036372a3336c4f2f4d2ce91a5f9cd18614

test:
  secret_key_base: 11ae78cdd02c6ab43e3d084289a6800c87b1cc271b10420d2378406f605891f45db9895468c71de0aa9680ee1e24cc0a11258676ea025a38e8e67ff8b7c1d152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
